             <li><a onclick="smilyfun(':)');"><img src="<?php echo $fullurl; ?>images/emoji/smiling.png"></a></li>
			 <li><a onclick="smilyfun(':smi:');"><img src="<?php echo $fullurl; ?>images/emoji/happy.png"></a></li>
             <li><a onclick="smilyfun('):');"><img src="<?php echo $fullurl; ?>images/emoji/unhappy.png"></a></li>
             <li><a onclick="smilyfun(';)');"><img src="<?php echo $fullurl; ?>images/emoji/surprised.png"></a></li>
             <li><a onclick="smilyfun(':win:');"><img src="<?php echo $fullurl; ?>images/emoji/wink.png"></a></li>
             <li><a onclick="smilyfun(':tno:');"><img src="<?php echo $fullurl; ?>images/emoji/tongue-out.png"></a></li>
             <li><a onclick="smilyfun(':sus:');"><img src="<?php echo $fullurl; ?>images/emoji/suspicious.png"></a></li>
             <li><a onclick="smilyfun(':srt:');"><img src="<?php echo $fullurl; ?>images/emoji/smart.png"></a></li>
             <li><a onclick="smilyfun(':set:');"><img src="<?php echo $fullurl; ?>images/emoji/secret.png"></a></li>
             <li><a onclick="smilyfun(':sd:');"><img src="<?php echo $fullurl;  ?>images/emoji/sad.png"></a></li>
             <li><a onclick="smilyfun(':qit:');"><img src="<?php echo $fullurl; ?>images/emoji/quiet.png"></a></li>
             <li><a onclick="smilyfun(':nnj:');"><img src="<?php echo $fullurl; ?>images/emoji/ninja.png"></a></li>
             <li><a onclick="smilyfun(':nrd:');"><img src="<?php echo $fullurl; ?>images/emoji/nerd.png"></a></li>
             <li><a onclick="smilyfun(':ned:');"><img src="<?php echo $fullurl; ?>images/emoji/mad.png"></a></li>
             <li><a onclick="smilyfun(':kis:');"><img src="<?php echo $fullurl; ?>images/emoji/kissing.png"></a></li>
             <li><a onclick="smilyfun(':lov:');"><img src="<?php echo $fullurl; ?>images/emoji/in-love.png"></a></li>
             <li><a onclick="smilyfun(':ill:');"><img src="<?php echo $fullurl; ?>images/emoji/ill.png"></a></li>
             <li><a onclick="smilyfun(':hp4:');"><img src="<?php echo $fullurl; ?>images/emoji/happy-4.png"></a></li>
             <li><a onclick="smilyfun(':hp3:');"><img src="<?php echo $fullurl; ?>images/emoji/happy-3.png"></a></li>
             <li><a onclick="smilyfun(':hp2:');"><img src="<?php echo $fullurl; ?>images/emoji/happy-2.png"></a></li>
             <li><a onclick="smilyfun(':hp1:');"><img src="<?php echo $fullurl; ?>images/emoji/happy-1.png"></a></li>
             <li><a onclick="smilyfun(':emt:');"><img src="<?php echo $fullurl; ?>images/emoji/emoticons.png"></a></li>
             <li><a onclick="smilyfun(':cr:');"><img src="<?php echo $fullurl; ?>images/emoji/crying.png"></a></li>
             <li><a onclick="smilyfun(':con:');"><img src="<?php echo $fullurl; ?>images/emoji/confused.png"></a></li>
             <li><a onclick="smilyfun(':bo:');"><img src="<?php echo $fullurl; ?>images/emoji/bored.png"></a></li>
             <li><a onclick="smilyfun(':brd:');"><img src="<?php echo $fullurl; ?>images/emoji/bored-2.png"></a></li>
             <li><a onclick="smilyfun(':br1:');"><img src="<?php echo $fullurl; ?>images/emoji/bored-1.png"></a></li>
             <li><a onclick="smilyfun(':ang:');"><img src="<?php echo $fullurl; ?>images/emoji/angry.png"></a></li>